In [12]:
%%time
import cv2
import os
path = './daum_img/'
file_list = os.listdir(path)
file_list.remove('.DS_Store')
file_list.sort()
len(file_list)
error = []
for file in file_list:
#     print(file)
    try:
        img = cv2.imread(f'{path}/{file}')
        imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        contour = cv2.Canny(img, 50, 100) # 100, 200은 변경 가능한 인자 값
#         plt.imshow(contour, cmap='gray') # binary
#         plt.xticks([]); plt.yticks([])
#         plt.savefig(f'./contour_naver/{file}', dpi=200)
    except:
        continue

CPU times: user 22.3 s, sys: 3.17 s, total: 25.4 s
Wall time: 13.2 s


In [13]:
 #N x N numpy array (dimensions dont matter)
# contour    #your numpy array
contour_df = pd.DataFrame(contour)  #converting it to a pandas dataframe
contour_df.to_csv('./contour_vector/contour_daum.csv', index=False)
contour_df.tail()

0    1    2    3    4    5    6    7    8    9    ...  240  241  242  \
145    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
146    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
147    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
148    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
149    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

     243  244  245  246  247  248  249  
145    0    0    0    0    0    0    0  
146    0    0    0    0    0    0    0  
147    0    0    0    0    0    0    0  
148    0    0    0    0    0    0    0  
149    0    0    0    0    0    0    0  

[5 rows x 250 columns]

In [14]:
contour_df.describe()

0          1           2           3           4           5    \
count  150.00000  150.00000  150.000000  150.000000  150.000000  150.000000   
mean    23.80000   23.80000   25.500000   22.100000   27.200000   25.500000   
std     74.42775   74.42775   76.756282   71.983569   78.979396   76.756282   
min      0.00000    0.00000    0.000000    0.000000    0.000000    0.000000   
25%      0.00000    0.00000    0.000000    0.000000    0.000000    0.000000   
50%      0.00000    0.00000    0.000000    0.000000    0.000000    0.000000   
75%      0.00000    0.00000    0.000000    0.000000    0.000000    0.000000   
max    255.00000  255.00000  255.000000  255.000000  255.000000  255.000000   

              6           7          8           9    ...         240  \
count  150.000000  150.000000  150.00000  150.000000  ...  150.000000   
mean    22.100000   22.100000   23.80000   18.700000  ...   47.600000   
std     71.983569   71.983569   74.42775   66.696825  ...   99.692009   
min      0.000000    0.000000    0.00000    0.000000  ...    0.000000   
25%      0.000000    0.000000    0.00000    0.000000  ...    0.000000   
50%      0.000000    0.000000    0.00000    0.000000  ...    0.000000   
75%      0.000000    0.000000    0.00000    0.000000  ...    0.000000   
max    255.000000  255.000000  255.00000  255.000000  ...  255.000000   

              241         242         243         244         245        246  \
count  150.000000  150.000000  150.000000  150.000000  150.000000  150.00000   
mean    44.200000   42.500000   42.500000   37.400000   42.500000   28.90000   
std     96.849846   95.351258   95.351258   90.514414   95.351258   81.10576   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.00000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.00000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.00000   
75%      0.000000    0.000000    0.000000    0.000000    0.000000    0.00000   
max    255.000000  255.000000  255.000000  255.000000  255.000000  255.00000   

              247         248         249  
count  150.000000  150.000000  150.000000  
mean    22.100000   32.300000   15.300000  
std     71.983569   85.096925   60.762023  
min      0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000  
50%      0.000000    0.000000    0.000000  
75%      0.000000    0.000000    0.000000  
max    255.000000  255.000000  255.000000  

[8 rows x 250 columns]

In [1]:
%%time
import cv2
import os
path = './naver_img/'
file_list = os.listdir(path)
file_list.remove('.DS_Store')
file_list.sort()
len(file_list)
error = []
for file in file_list:
#     print(file)
    try:
        img = cv2.imread(f'{path}/{file}')
        imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        contour = cv2.Canny(img, 50, 100) # 100, 200은 변경 가능한 인자 값
#         print(contour)
#         plt.imshow(contour, cmap='gray') # binary
#         plt.xticks([]); plt.yticks([])
#         plt.savefig(f'./contour_naver/{file}', dpi=200)
    except:
        continue

CPU times: user 49 s, sys: 8.56 s, total: 57.6 s
Wall time: 25.1 s


In [10]:
#N x N numpy array (dimensions dont matter)
# contour    #your numpy array
contour_df = pd.DataFrame(contour)  #converting it to a pandas dataframe
contour_df.to_csv('./contour_vector/contour_naver.csv', index=False)
contour_df.tail()

0    1    2    3    4   5    6    7   8   9   ...   61  62   63   64  \
37    0  255    0    0    0   0  255    0   0   0  ...  255   0  255  255   
38    0  255  255    0    0   0    0    0   0   0  ...    0   0    0  255   
39    0    0  255    0    0   0    0    0   0   0  ...  255   0    0  255   
40    0    0  255  255    0   0    0    0   0   0  ...    0   0  255    0   
41  255  255    0  255  255   0  255  255   0   0  ...    0   0  255    0   

     65  66  67   68   69   70  
37    0   0   0    0    0    0  
38    0   0   0    0  255  255  
39  255   0   0  255  255    0  
40  255   0   0  255    0    0  
41  255   0   0  255    0    0  

[5 rows x 71 columns]

In [11]:
contour_df.describe()

0           1           2           3           4           5   \
count   42.000000   42.000000   42.000000   42.000000   42.000000   42.000000   
mean    48.571429   60.714286   72.857143   66.785714   66.785714   54.642857   
std    101.346338  109.925537  116.593639  113.475158  113.475158  105.901432   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
75%      0.000000    0.000000  255.000000  191.250000  191.250000    0.000000   
max    255.000000  255.000000  255.000000  255.000000  255.000000  255.000000   

               6           7           8           9   ...          61  \
count   42.000000   42.000000   42.000000   42.000000  ...   42.000000   
mean    60.714286   54.642857   85.000000   54.642857  ...  127.500000   
std    109.925537  105.901432  121.665275  105.901432  ...  129.045511   
min      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
25%      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
50%      0.000000    0.000000    0.000000    0.000000  ...  127.500000   
75%      0.000000    0.000000  255.000000    0.000000  ...  255.000000   
max    255.000000  255.000000  255.000000  255.000000  ...  255.000000   

               62          63          64          65          66          67  \
count   42.000000   42.000000   42.000000   42.000000   42.000000   42.000000   
mean    72.857143  109.285714   91.071429  109.285714   42.500000   54.642857   
std    116.593639  127.721932  123.666229  127.721932   96.184845  105.901432   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
75%    255.000000  255.000000  255.000000  255.000000    0.000000    0.000000   
max    255.000000  255.000000  255.000000  255.000000  255.000000  255.000000   

               68          69          70  
count   42.000000   42.000000   42.000000  
mean    85.000000   78.928571   78.928571  
std    121.665275  119.314790  119.314790  
min      0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000  
50%      0.000000    0.000000    0.000000  
75%    255.000000  255.000000  255.000000  
max    255.000000  255.000000  255.000000  

[8 rows x 71 columns]

In [17]:
%%time
import cv2
import os
path = './daum_img/'
file_list = os.listdir(path)
file_list.remove('.DS_Store')
file_list.sort()
len(file_list)
error = []
for file in file_list[:5]:
#     print(file)
    try:
        img = cv2.imread(f'{path}/{file}')
        imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        contour = cv2.Canny(img, 50, 100) # 100, 200은 변경 가능한 인자 값
        print(contour)
#         plt.imshow(contour, cmap='gray') # binary
#         plt.xticks([]); plt.yticks([])
#         plt.savefig(f'./contour_naver/{file}', dpi=200)
    except:
        continue

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
CPU times: user 23.8 ms, sys: 15.3 ms, total: 39.1 ms
Wall time: 29.3 ms


In [15]:
%%time
import cv2
import os
path = './naver_img/'
file_list = os.listdir(path)
file_list.remove('.DS_Store')
file_list.sort()
len(file_list)
error = []
for file in file_list[:3]:
#     print(file)
    try:
        img = cv2.imread(f'{path}/{file}')
        imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        contour = cv2.Canny(img, 50, 100) # 100, 200은 변경 가능한 인자 값
        print(contour)
#         plt.imshow(contour, cmap='gray') # binary
#         plt.xticks([]); plt.yticks([])
#         plt.savefig(f'./contour_naver/{file}', dpi=200)
    except:
        continue

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[255 255   0 ... 255   0   0]
 [  0 255 255 ... 255 255   0]
 [255   0   0 ...   0 255 255]
 ...
 [  0   0   0 ... 255   0 255]
 [  0   0   0 ... 255   0   0]
 [  0   0   0 ... 255   0   0]]
CPU times: user 32.4 ms, sys: 34.7 ms, total: 67.1 ms
Wall time: 102 ms
