### 네이버 웹툰 줄거리와 다음 웹툰 줄거리 사이의 거리
#### 유클리드 거리

In [41]:
import pandas as pd

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_colwidth', -1)

# load file
df_naver = pd.read_csv('naver_webtoon_info.csv')
df_naver.tail()

Unnamed: 0            title     genre  \
328  328         그녀의 버킷리스트, 황양&솦  스토리, 드라마   
329  329         선녀야 야옹해봐!, 햄톨탱크  스토리, 로맨스   
330  330         갓!김치, 김민우        에피소드, 개그   
331  331         속삭이는 e로맨스, 최경아   스토리, 로맨스   
332  332         호곡, 감대           스토리, 판타지   

                                             content      age  
328  미련없는 죽음을 위한그녀의 완벽한 버킷리스트                         12세 이용가  
329  사랑 인연을 이어주기 위해 지상에 온 선녀 초미.톱스타 강수에게 냥줍을 당하다..!!  전체연령가    
330  ​1000% 신토불이 히어로 등장!                              전체연령가    
331  불면증에 걸린 남자와 책만 읽으면 모두를 잠들게하는 여자가 만났다.            전체연령가    
332  '이제 우리 차례야'조선의 왕 '천군'이 사라지고 3년 뒤...한 소녀가 나타나다.   12세 이용가

**데이터 전처리**
- 모든 genre에 있는 '스토리' 제거
- 특수기호 제거
- genre 기준 정렬

In [2]:
# genre내부 '스토리' 제거 후 category : content로 진행
# 1. genre에 '스토리' 제거한 폴더를 genre1으로 새로 생성
genre = []
for g in df_naver['genre']:
    genre.append(g.split()[1])
# print(genre)

In [3]:
df_naver['genre1'] = genre
# content 내부 특수기호 제거
df_naver['content1'] = df_naver['content'].str.replace(pat=r'[%\.\,\?\!\♥\‘\’\'\~\(\)\…\"\<\>\/\+\※\r\n\-\[\]\u200b\']', repl=r'', regex=True)
columns = ['title', 'genre1', 'content1']
df_naver = pd.DataFrame(df_naver, columns=columns)

df_naver.tail()

title genre1                                    content1
328  그녀의 버킷리스트, 황양&솦  드라마    미련없는 죽음을 위한그녀의 완벽한 버킷리스트                  
329  선녀야 야옹해봐!, 햄톨탱크  로맨스    사랑 인연을 이어주기 위해 지상에 온 선녀 초미톱스타 강수에게 냥줍을 당하다
330  갓!김치, 김민우        개그     1000 신토불이 히어로 등장                          
331  속삭이는 e로맨스, 최경아   로맨스    불면증에 걸린 남자와 책만 읽으면 모두를 잠들게하는 여자가 만났다      
332  호곡, 감대           판타지    이제 우리 차례야조선의 왕 천군이 사라지고 3년 뒤한 소녀가 나타나다

In [4]:
# genre1 기준 정렬
df_naver.sort_values('genre1', ascending=True).tail()

title genre1  \
157  꽃만 키우는데 너무강함, 쿰타타&주현후  판타지     
154  가담항설, 랑또               판타지     
153  화이트 블러드, 임리나           판타지     
201  트럼프, 이채은               판타지     
332  호곡, 감대                 판타지     

                                                                 content1  
157  황재호는 자신의 꿈인 꽃집을 차리기 위해 게임을 시작하게 되는데게임 속에서 꽃집을 운영하기 위한 재호의 긴 여정이 시작된다  
154  이번 주인공은 돌이다돌이지만 동료도 모으고 악당도 물리친다랑또 작가표 동양 판타지 소년만화                    
153  스타일리쉬 뱀파이어 액션그리고 처절한 로맨스                                              
201  사형 위기에 직면한 수배범 아버지와 세상 누구보다 존경하는 단장님 사이소년의 갈등이 시작된다 트럼프 시즌4           
332  이제 우리 차례야조선의 왕 천군이 사라지고 3년 뒤한 소녀가 나타나다

In [5]:
# genre1을 기준으로 groupby
df_n = df_naver.groupby('genre1').apply(lambda x: x.sum())
df_n = df_n.replace('감성감성감성', '감성').replace('개그개그개그개그개그개그개그개그개그개그개그개그개그개그개그개그개그개그', '개그').replace('드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마드라마', '드라마').replace('로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스로맨스', '로맨스').replace('스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러스릴러', '스릴러').replace('스포츠스포츠스포츠스포츠스포츠스포츠', '스포츠').replace('시대극시대극시대극시대극시대극', '시대극').replace('액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션액션', '액션').replace('일상일상일상일상일상일상일상일상일상일상일상일상일상', '일상').replace('판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지판타지', '판타지')
df_n.head()

title  \
genre1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
감성      숲속의 담, 다홍나의 첫번째 새벽, 신매마음의 숙제, 고아라                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
개그      사장님을 잠금해제, 박성현마음의소리, 조석문래빗, 이난필살VS로맨스, 구르조선홍보대행사 조대박, 김양수모죠의 일지컷툰, 모죠언덕 위의 제임스, 쿠당탕203호 저승사자, 샤니어쩐지 수상하더라, 디기사&두둥만물의 영장, 보민무모협지, 초신우갑자기 커피, 우&리지가슴털 로망스, 갸오오후덜덜덜 남극전자, 김민혁모죠의 일지컷툰, 모죠호랭총각, 강호진닭강정, 박지독갓!김치, 김민우                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
드라마     소녀의 세계, 모랑지평범한 8반, 영파카백수세끼, 치즈니편내편, 미티칼가는 소녀, 오리요리GO, HO9이것도 친구라고, 제야일진이 사나워, 강환영&김현아교환일기, 한끼룩와이키키 뱀파이어, 요니요니피플, 서승준&손창균위대한 방옥숙, 매미&희세결백한 사람은 없다, 서각중독연구소, 김택기인간의 온도, 이재익&양세준물레, 고긱랜덤채팅의 그녀!, 박은혁체크포인트, 송가&은소은주의 방 2~3부, 노란구미중증외상센터 : 골든 아워, 한산이가&홍비치라견우와 선녀, 안수민열정호구, 솔뱅이땅 보고 걷는 아이, 다온너에게만 보이는, 소소만집이 없어, 와난그날 죽은 나는휴재, 이언별종, 이무기아이고 아이고, 하모정년이, 서이레&나몬복학왕, 기안84연놈, 상하세상은 돈과 권력, 한동우&이도희여주실격!, 기맹기귀곡의 문, 삼촌갓물주, HD3얼굴천재, 지에이정순애 식당, 아르몽당신의 향수, 호우오라존미, 허5파6텃밭부 사건일지, 오이츄밀웜, 쿼시비스타, 유마저승사자 출입금지, 심웅섭연애혁명, 232좀비딸, 이윤창겟백, 세윤하드캐리휴재, 조양병의 기록, 베어리킬더킹, 마사토끼&joana당신의 과녁, 고태호셧업앤댄스, 이은재소녀180, 나우원&델라날 가져요, 로즈빈&원펀치래빗데이빗, d몬깁스맨, 맹물갓도령스, 도로롱열등의 조건, 또이외모지상주의, 박태준이제 곧 죽습니다, 이원식&꿀찬닥터 프로스트 시즌 3~4, 이종범1초, 시니&광운화장 지워주는 남자, 이연스윗솔티, 달삐복학생 정순이, 한짜장도롱이, 사이사9등급 뒤집기, 아백나쁜 쪽으로, 오은&이세릴대표님이 구독하셨습니다, 신지원&한혜린얌전한 사이, JQ&이진영프리드로우, 전선욱회춘, 기안84나를 바꿔줘, 이지호&호띠친애하는 X, 반지운고인의 명복, 조주희&유노왕세자 입학도, 무번누군가의 로섬, 방농구틴맘, theterm머리카락을 뽑으면, 이다몽11me, 고지애&영재영천사가 아니야, 박유나&표류어른의 계절, 선홍달맘

#### countvectorizer 
- 1. 문서를 토큰 리스트로 변환한다.
- 2. 각 문서에서 토큰의 출현 빈도를 센다.
- 3. 각 문서를 BOW 인코딩 벡터로 변환한다. 

In [42]:
# 문장 사이 거리 구하기
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(min_df=1)

In [44]:
# 거리를 구하는 것이므로 지도할 내용이 없음
# 훈련용 문장
contents = list(df_naver['content'])
# contents

In [45]:
# 형태소 분석
from konlpy.tag import Okt

t = Okt()
def tw_tokenizer(text):
    tokens_ko = t.morphs(text)
    return tokens_ko

In [46]:
contents_tokens = [t.morphs(row) for row in contents]
len(contents_tokens)

333

In [47]:
# 형태소 분석 결과를 하나의 문장으로 합침
# 논란의 여지가 있음, 데이터가 많으면 문제가 됨
contents_for_vectorize = []

for content in contents_tokens:
    sentence = ''
    for word in content:
        sentence = sentence + ' ' + word
        
    contents_for_vectorize.append(sentence)
    
# contents_for_vectorize

In [48]:
# abs벡터라이즈
X = vectorizer.fit_transform(contents_for_vectorize)
X

<333x2286 sparse matrix of type '<class 'numpy.int64'>'
	with 4062 stored elements in Compressed Sparse Row format>

In [49]:
# 10개의 문장, 전체 말뭉치의 단어 2316개
num_samples, num_features = X.shape
num_samples, num_features

(333, 2286)

In [13]:
# 확인
# vectorizer.get_feature_names()

['100',
 '1000',
 '100년',
 '10년',
 '11',
 '12년',
 '13',
 '13년',
 '15',
 '15년',
 '17',
 '17년',
 '184',
 '1926년',
 '1년',
 '1등',
 '1일',
 '20',
 '2000년',
 '2015',
 '2017',
 '2019',
 '202',
 '21',
 '22',
 '24시간',
 '27',
 '29',
 '2등',
 '30분',
 '39',
 '3년',
 '430년',
 '44',
 '500년',
 '58',
 '5년',
 '7년',
 '8년',
 '9등',
 'ai',
 'ceo',
 'cm',
 'dice',
 'gp',
 'kpop',
 'npc',
 'out',
 'rpg',
 'sf',
 'sns',
 'vs',
 '가게',
 '가고',
 '가기',
 '가까워진',
 '가까워질',
 '가난한',
 '가는',
 '가능해져',
 '가던',
 '가득',
 '가람',
 '가려내는',
 '가려진',
 '가르치는',
 '가린',
 '가수',
 '가슴',
 '가에',
 '가온',
 '가우리',
 '가운데',
 '가장',
 '가정',
 '가져간',
 '가져요',
 '가족',
 '가지',
 '가진',
 '가표',
 '각성',
 '각자',
 '간데',
 '간의',
 '간이',
 '간첩',
 '간호사',
 '갇힌',
 '갈등',
 '갈아',
 '갈취',
 '감당',
 '감독',
 '감동',
 '감성',
 '감옥',
 '감정',
 '감춰져있던',
 '갑사',
 '갑자기',
 '갑작스러운',
 '갓길',
 '갔다가',
 '강룡',
 '강성재',
 '강수',
 '강시',
 '강유',
 '강제',
 '강풍',
 '강한',
 '강해지는',
 '강혁',
 '강호',
 '갖고',
 '같다나는',
 '같은',
 '같은건',
 '같이',
 '개그',
 '개념',
 '개미',
 '개발',
 '개월',
 '개인',
 '개조',
 '갱생',
 '거꾸로',
 '거대',
 '거대한',
 '거대해지는',


In [50]:
# toarray
X.toarray().transpose()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [51]:
# 테스트용 문장 : 다음 웹툰 설명 문장
new_post = ['묘약으로 시작된 기간한정 연애, 두 형제를 사로 잡아버린 마녀의 후예']
new_post_tokens = [t.morphs(row) for row in new_post]
            
new_post_for_vectorize = []

for content in new_post_tokens:
    sentence = ''
    for word in content:
        sentence = sentence + ' ' + word
        
    new_post_for_vectorize.append(sentence)
        
new_post_for_vectorize

[' 묘약 으로 시작 된 기간 한정 연애 , 두 형제 를 사 로 잡아 버린 마녀 의 후예']

In [52]:
# 벡터로 표현
new_post_vec = vectorizer.transform(new_post_for_vectorize)
new_post_vec.toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [53]:
# 유클리드 거리
import scipy as sp

def dist_raw(v1, v2):
    delta = v1 - v2
    return sp.linalg.norm(delta.toarray())

In [54]:
# 결과
dist = [dist_raw(each, new_post_vec) for each in X]
dist

[4.47213595499958,
 3.4641016151377544,
 4.47213595499958,
 4.795831523312719,
 4.123105625617661,
 6.0,
 3.4641016151377544,
 4.47213595499958,
 4.123105625617661,
 3.605551275463989,
 5.477225575051661,
 5.830951894845301,
 4.123105625617661,
 4.58257569495584,
 5.385164807134504,
 3.872983346207417,
 6.557438524302,
 3.605551275463989,
 4.123105625617661,
 4.123105625617661,
 3.872983346207417,
 3.605551275463989,
 4.358898943540674,
 4.0,
 3.3166247903554,
 4.47213595499958,
 3.605551275463989,
 4.242640687119285,
 5.196152422706632,
 5.291502622129181,
 3.605551275463989,
 6.324555320336759,
 3.872983346207417,
 4.795831523312719,
 4.69041575982343,
 3.7416573867739413,
 4.358898943540674,
 4.123105625617661,
 5.196152422706632,
 5.291502622129181,
 4.0,
 6.4031242374328485,
 3.7416573867739413,
 4.795831523312719,
 6.855654600401044,
 3.4641016151377544,
 4.123105625617661,
 6.48074069840786,
 4.0,
 4.123105625617661,
 3.7416573867739413,
 4.358898943540674,
 4.0,
 4.898979485566

In [55]:
print("Best post is ", dist.index(min(dist)), ", dist = ", min(dist))
print("test post is : ", new_post)
print("best dist post is : ", contents[dist.index(min(dist))])

Best post is  86 , dist =  2.8284271247461903
test post is :  ['묘약으로 시작된 기간한정 연애, 두 형제를 사로 잡아버린 마녀의 후예']
best dist post is :  너의 지독한 덫에 빠져들다.


In [39]:
df_naver.tail()

title genre1                                    content1
328  그녀의 버킷리스트, 황양&솦  드라마    미련없는 죽음을 위한그녀의 완벽한 버킷리스트                  
329  선녀야 야옹해봐!, 햄톨탱크  로맨스    사랑 인연을 이어주기 위해 지상에 온 선녀 초미톱스타 강수에게 냥줍을 당하다
330  갓!김치, 김민우        개그     1000 신토불이 히어로 등장                          
331  속삭이는 e로맨스, 최경아   로맨스    불면증에 걸린 남자와 책만 읽으면 모두를 잠들게하는 여자가 만났다      
332  호곡, 감대           판타지    이제 우리 차례야조선의 왕 천군이 사라지고 3년 뒤한 소녀가 나타나다

In [57]:
df_naver[df_naver['content']  == '너의 지독한 덫에 빠져들다.'] 

Unnamed: 0     title     genre          content      age
86  86          올가미, 해무리  스토리, 스릴러  너의 지독한 덫에 빠져들다.  15세 이용가

In [58]:
# 유사도 - 벡터 사이의 거리
for i in range(0, len(contents)):
    print(X.getrow(i).toarray())

print('-'*70)
print(new_post_vec.toarray())

[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[1 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]


### 네이버 웹툰 줄거리와 다음 웹툰 줄거리 사이의 거리
#### TF-IDF 인코딩 방법
- Term Frequency - Inverse Document Frequency
- 모든 문서에 공통적으로 들어있는 단어의 경우 문서 구별 능력이 떨어진다고 보아 가중치를 축소하는 방법
- $$\text{tf-idf}(d, t) = \text{tf}(d, t) \cdot \text{idf}(t)$$
- tf(d, t): 특정 단어의 빈도수
- $$\text{idf}(d, t) = \log \dfrac{n}{1 + \text{df}(t)}$$
- idf(t) : 특정 단어가 들어있는 문서의 수에 반비례하는 수
- n : 전체 문서의 수
- df(t) : 단어 t를 가진 문서의 수

In [60]:
# 거리를 구하는 것이므로 지도할 내용이 없음
# 훈련용 문장
contents = list(df_naver['content'])
# contents

In [68]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(min_df=0, decode_error='ignore')

In [69]:
# 다시 적용
X = vectorizer.fit_transform(contents_for_vectorize)
num_samples, num_features = X.shape
num_samples, num_features

(333, 2286)

In [70]:
# 내용 확인
# X.toarray().transpose()

In [71]:
# 테스트 문장 적용
new_post_vec = vectorizer.transform(new_post_for_vectorize)
new_post_vec.toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [72]:
def dist_norm(v1, v2):
    v1_normalized = v1 / sp.linalg.norm(v1.toarray())
    v2_normalized = v2 / sp.linalg.norm(v2.toarray())
    
    delta = v1_normalized - v2_normalized
    
    return sp.linalg.norm(delta.toarray())

In [73]:
# 결과
dist = [dist_norm(each, new_post_vec) for each in X]

print("Best post is ", dist.index(min(dist)), ", dist = ", min(dist))
print("test post is : ", new_post)
print("best dist post is : ", contents[dist.index(min(dist))])

Best post is  161 , dist =  1.3004911997134059
test post is :  ['묘약으로 시작된 기간한정 연애, 두 형제를 사로 잡아버린 마녀의 후예']
best dist post is :  모든 게 서툴고 어색했던 중학교 2학년 15살의 첫 연애.그렇게 헤어졌던 첫사랑을 같은 대학, 자취방 바로 옆집에서 다시 마주하다! 사랑이 뭔지, 연애가 뭔지 아직도 헷갈리고 서툴기만 한 스무 살. 과연 이번엔스스로에게 당당하고 서로를 솔직하게 마주하는 연애에 성공할 수 있을까?


In [75]:
df_naver[df_naver['content']  == '모든 게 서툴고 어색했던 중학교 2학년 15살의 첫 연애.그렇게 헤어졌던 첫사랑을 같은 대학, 자취방 바로 옆집에서 다시 마주하다! 사랑이 뭔지, 연애가 뭔지 아직도 헷갈리고 서툴기만 한 스무 살. 과연 이번엔스스로에게 당당하고 서로를 솔직하게 마주하는 연애에 성공할 수 있을까?'] 

Unnamed: 0      title     genre  \
161  161         가타부타타, 숭어  스토리, 로맨스   

                                                                                                                                                          content  \
161  모든 게 서툴고 어색했던 중학교 2학년 15살의 첫 연애.그렇게 헤어졌던 첫사랑을 같은 대학, 자취방 바로 옆집에서 다시 마주하다! 사랑이 뭔지, 연애가 뭔지 아직도 헷갈리고 서툴기만 한 스무 살. 과연 이번엔스스로에게 당당하고 서로를 솔직하게 마주하는 연애에 성공할 수 있을까?   

       age  
161  전체연령가

In [32]:
df_naver.head()

title genre1  \
0  신의 탑, SIU      판타지     
1  윈드브레이커, 조용석    스포츠     
2  인생존망, 박태준&전선욱  액션      
3  소녀의 세계, 모랑지    드라마     
4  평범한 8반, 영파카    드라마     

                                                       content1  
0  자신의 모든 것이었던 소녀를 쫓아 탑에 들어온 소년그리고 그런 소년을 시험하는 탑                 
1  자유를 꿈꾸는 청춘들의 스트릿라이딩 드라마                                       
2  학교 다닐때 그렇게 놀았으면 졸업하고 지금은 불행해야하는거 아니야너 때문에 망한 내인생 너도 한번 당해봐    
3  완벽해 보이지만 사실 외로웠던 백조들과 맘씨 착한 오리가 만나여러 갈등을 함께 겪으며 진짜 친구가 되어가는데  
4  안 평범한 아이들이 모인 평범한 8반고품격 웰메이드 병맛을 느껴보세요

In [35]:
df_naver[['title']][:1].values

array([['신의 탑, SIU']], dtype=object)

#### 나이브베이즈를 활용한 유사문서 검색
- 트레인 셋 : 네이버 웹툰 정보
- 테스트 셋 : 다음 웹툰 정보

In [178]:
# Accuracy 확인
from sklearn.metrics import accuracy_score

y_pred_tr = pipe.predict(x_train)
y_pred_test = pipe.predict(x_test)
print('Train Acc : ', accuracy_score(y_train, y_pred_tr))
print('Test Acc : ', accuracy_score(y_test, y_pred_test))

NameError: name 'pipe' is not defined

In [178]:
# Accuracy 확인
from sklearn.metrics import accuracy_score

y_pred_tr = pipe.predict(x_train)
y_pred_test = pipe.predict(x_test)
print('Train Acc : ', accuracy_score(y_train, y_pred_tr))
print('Test Acc : ', accuracy_score(y_test, y_pred_test))

NameError: name 'pipe' is not defined

In [123]:
# 지도학습 랜덤으로 shuffle 해야 하는지?
categories = ['감성', '개그', '드라마', '로맨스', '스릴러', '스포츠', 
             '시대극', '액션', '일상', '판타지']
naver_webtoon_train = df_n(subset='content1', 
                                 categories=categories, 
                                 shuffle=True,
                                 random_state=13)

TypeError: 'DataFrame' object is not callable

In [124]:
# columns name
df_n.keys()

Index(['title', 'genre1', 'content1'], dtype='object')

In [125]:
# 타겟을 0, 1, 2, 3과 같은 숫자로 해야 하는지? 문자로 변환해도 되는지?
df_n.genre1

genre1
감성     감성 
개그     개그 
드라마    드라마
로맨스    로맨스
스릴러    스릴러
스포츠    스포츠
시대극    시대극
액션     액션 
일상     일상 
판타지    판타지
Name: genre1, dtype: object

In [126]:
# 데이터 
df_n['content1']

genre1
감성     어느 순간부터 성장이 멈춘 담은사람들을 피해 숲속으로 떠난다너에게 작은 용기를 줄게하늘을 나는 소년을 만난 소녀의 이야기13년 전 사라진 나의 첫사랑흡혈귀가 되어 돌아왔다                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

In [194]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(df_n.content1)
print(X_train_counts.shape)
# count_vect.vocabulary_ 

(10, 2807)


{'어느': 1674,
 '순간부터': 1442,
 '성장이': 1340,
 '멈춘': 880,
 '담은사람들을': 538,
 '피해': 2629,
 '숲속으로': 1458,
 '떠난다너에게': 730,
 '작은': 2137,
 '용기를': 1841,
 '줄게하늘을': 2323,
 '나는': 409,
 '소년을': 1378,
 '만난': 828,
 '소녀의': 1366,
 '이야기13년': 1956,
 '사라진': 1193,
 '나의': 423,
 '첫사랑흡혈귀가': 2458,
 '되어': 655,
 '돌아왔다': 609,
 '얼떨결에': 1696,
 '죽어': 2308,
 '스마트폰이': 1465,
 '39살': 26,
 '대기업': 550,
 '천재': 2450,
 'ceo': 39,
 '선주얼떨결에': 1324,
 '스마트폰을': 1464,
 '주운': 2298,
 '29살': 19,
 '취준생': 2504,
 '인성아홉수': 2027,
 '사람이': 1204,
 '힘을': 2806,
 '합쳐': 2705,
 '살인범을': 1247,
 '찾는다솔직': 2424,
 '담백': 537,
 '최강의': 2479,
 '개그': 108,
 '만화': 848,
 '마음의': 800,
 '소리날': 1383,
 '가져요': 69,
 '엉엉수': 1714,
 '세기': 1346,
 '용왕에게': 1843,
 '몰락한': 923,
 '토끼일족피의': 2561,
 '복수를': 1120,
 '위해': 1887,
 '전학': 2213,
 '인간': 2010,
 '병기': 1096,
 '도생원의': 594,
 '해신고': 2710,
 '정복기무협': 2229,
 '같은': 106,
 '여자': 1730,
 '유비': 1896,
 '순정': 1446,
 '남자': 449,
 '신우자신의': 1541,
 '장르대로': 2159,
 '살아가던': 1242,
 '사람의': 1203,
 '순탄치': 1448,
 '않은': 1646,
 '썸타기만화의': 1576,
 '정석대로': 2231

#### TF-IDF 인코딩
- Term Frequency - Inverse Document Frequency
- 모든 문서에 공통적으로 들어있는 단어의 경우 문서 구별 능력이 떨어진다고 보아 가중치를 축소하는 방법
- $$\text{tf-idf}(d, t) = \text{tf}(d, t) \cdot \text{idf}(t)$$
- tf(d, t): 특정 단어의 빈도수
- $$\text{idf}(d, t) = \log \dfrac{n}{1 + \text{df}(t)}$$
- idf(t) : 특정 단어가 들어있는 문서의 수에 반비례하는 수
- n : 전체 문서의 수
- df(t) : 단어 t를 가진 문서의 수

In [128]:
# Tfidf 적용
from sklearn.feature_extraction.text import TfidfTransformer

tf_transformer = TfidfTransformer(use_idf=False).fit(X_train_counts)
X_train_tf = tf_transformer.transform(X_train_counts)
X_train_tf.shape

(10, 2807)

In [179]:
# Multinomial Naive Bayes 적용
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(X_train_tf, df_n.genre1)

In [180]:
# 네이버 웹툰 소개 글 Test
docs_new = ['자신의 모든 것이었던 소녀를 쫓아 탑에 들어온 소년 그리고 그런 소년을 시험하는 탑', \
            '누구에게나 비밀은 있다! 그렇다면 여신에게는 어떤 비밀이?!']
X_new_counts = count_vect.transform(docs_new)
X_new_tfidf = tf_transformer.transform(X_new_counts)

predicted = clf.predict(X_new_tfidf)

for doc, category in zip(docs_new, predicted):
    print('%r => %s' % (doc, df_n.genre1[category]))

'자신의 모든 것이었던 소녀를 쫓아 탑에 들어온 소년 그리고 그런 소년을 시험하는 탑' => 판타지
'누구에게나 비밀은 있다! 그렇다면 여신에게는 어떤 비밀이?!' => 로맨스


In [177]:
# 파이프 라인 생성
from sklearn.pipeline import Pipeline

text_clf = Pipeline([
    ('vect', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('clf', MultinomialNB()),
])

#### 다음 웹툰 정보
- 테스트 데이터

In [165]:
df_daum = pd.read_csv('daum_webtoon_info.csv')
df_daum.tail()

Unnamed: 0       nickname    title   genre  \
162  162         nightperfume   밤의 향     순정,성인    
163  163         favorite       취향저격 그녀  순정,드라마   
164  164         BurningEffect  버닝 이펙트   액션,판타지   
165  165         ficnonfic      퀴퀴한 일기   코믹,일상    
166  166         parody         채널뽁스     코믹,지식    

                                             content  age  
162  당신의 살내음과 여름밤의 향기를 난 평생 잊지 않을 거에요                 19   
163  그의 심장을 저격하기 위해 뭉친 둘의 비밀스런 동거 라이프!                0    
164  '죄를 짓는 자는 죽는다.' 법을 집행하는 자와 세상을 뒤엎으려는 자들의 치열한 싸움  0    
165  즈질스럽고 퀴퀴한 언니의 쿰쿰한 일상다반사                          0    
166  상상 그 이상의 요절복통 코미디 멀티플렉스 <채널뽁스>                   0

In [118]:
df_daum['genre'].unique()

array(['드라마,일상', '무협,액션', '순정,드라마', '순정,학원', '미스터리,스릴러', '일상,학원',
       '코믹,드라마', '액션,판타지', '학원,코믹', '코믹,액션', '드라마,액션', '스릴러,드라마',
       '드라마,미스터리', '스릴러,공포', '코믹,학원', '미스터리', '판타지,액션', '스릴러,성인', '코믹,일상',
       '드라마,스릴러', '드라마', '드라마,판타지,순정', '드라마,판타지', '드라마,지식', '공포,스릴러',
       '스포츠,학원', '판타지,순정', '순정,지식', '드라마,코믹', '드라마,학원', '무협,판타지',
       '판타지,드라마', '순정,판타지', '액션,스릴러', '순정,성인', '스릴러,학원', '순정', '코믹,성인',
       '스릴러,미스터리', '학원,순정', '일상,코믹', '액션,드라마', '판타지,스릴러', '스포츠,드라마',
       '성인,드라마', '공포,드라마', '학원,액션', '액션,학원', '미스터리,판타지', '드라마,순정',
       '판타지,성인', '학원,스포츠', '스릴러,액션', '액션,무협', '순정,코믹', '무협,드라마', '코믹,지식'],
      dtype=object)

In [166]:
# genre내부 '스토리' 제거 후 category : content로 진행
# 1. genre에 '스토리' 제거한 폴더를 genre1으로 새로 생성
genre = []
for g in df_daum['genre']:
    genre.append(g.split()[0][:3])
print(genre)

['드라마', '무협,', '순정,', '순정,', '미스터', '일상,', '코믹,', '액션,', '학원,', '코믹,', '드라마', '스릴러', '드라마', '순정,', '스릴러', '코믹,', '미스터', '판타지', '순정,', '스릴러', '액션,', '스릴러', '액션,', '코믹,', '판타지', '순정,', '순정,', '순정,', '액션,', '드라마', '드라마', '순정,', '드라마', '무협,', '드라마', '드라마', '공포,', '순정,', '스포츠', '스릴러', '판타지', '순정,', '드라마', '드라마', '무협,', '드라마', '드라마', '판타지', '드라마', '스릴러', '판타지', '액션,', '순정,', '코믹,', '순정,', '순정,', '순정,', '드라마', '순정,', '액션,', '스릴러', '순정,', '순정,', '스릴러', '스릴러', '순정', '판타지', '액션,', '판타지', '드라마', '코믹,', '판타지', '판타지', '판타지', '스릴러', '스포츠', '학원,', '일상,', '미스터', '순정,', '순정,', '순정,', '스릴러', '스릴러', '판타지', '액션,', '판타지', '드라마', '순정,', '판타지', '판타지', '순정,', '판타지', '순정,', '코믹,', '스포츠', '코믹,', '코믹,', '순정,', '일상,', '성인,', '드라마', '공포,', '일상,', '액션,', '드라마', '순정,', '드라마', '학원,', '순정,', '액션,', '미스터', '드라마', '코믹,', '순정,', '판타지', '드라마', '판타지', '코믹,', '순정,', '학원,', '순정,', '학원,', '드라마', '코믹,', '순정,', '순정,', '드라마', '판타지', '순정,', '코믹,', '드라마', '드라마', '순정,', '액션,', '스릴러', '액션,', '판타지', '드라마', '액션,', '드라마', '일상,', '코믹,',

In [174]:
df_daum['genre1'] = genre
# content 내부 특수기호 제거
df_daum['content1'] = df_daum['content1'].str.replace(pat=r'[%\.\,\?\!\♥\‘\’\'\~\(\)\…\"\<\>\/\+\※\r\n\-\[\]\u200b\']', repl=r'', regex=True)
df_daum['genre1'] = df_daum['genre1'].str.replace(pat=r'[,]', repl=r'', regex=True)
columns = ['title', 'genre1', 'content1']
df_daum = pd.DataFrame(df_daum, columns=columns)

df_daum

title genre1  \
0    현세이의 보이는 라디오         드라마     
1    강호표사                 무협      
2    사귄 건 아닌데             순정      
3    하나밖에 안 보여!           순정      
4    메모리스트                미스터     
5    쓰레기 머학생              일상      
6    어름치                  코믹      
7    식귀                   액션      
8    아싸가 알아버렸다            학원      
9    찬란한 액션 유치원           코믹      
10   정상회담 : 스틸레인3         드라마     
11   흑우                   스릴러     
12   타원을 그리는 법            드라마     
13   교수님을 빚는 중            순정      
14   조류공포증                스릴러     
15   이대로 멈출 순 없다          코믹      
16   망자의 서                미스터     
17   그라티아                 판타지     
18   굿바이 사돈!              순정      
19   리세터                  스릴러     
20   노동본색                 액션      
21   집행자여                 스릴러     
22   NR 뉴월드               액션      
23   일단 질러! 질렐루야          코믹      
24   트레이스                 판타지     
25   비밀 사이                순정      
26   아싸클럽                 순정      
27   너를 만나다               순정      
28   뱀파이어 신드롬             액션      
29   화폐개혁                 드라마     
30   이태원 클라쓰              드라마     
31   그녀의 앵무새              순정      
32   닥터 파인의 하루            드라마     
33   단두(斷頭)               무협      
34   해오와 사라               드라마     
35   신성한, 이혼              드라마     
36   멸종인간                 공포      
37   우리집이거든요!             순정      
38   학교대표                 스포츠     
39   거울 죽이기               스릴러     
40   헬로 마이 안드로이드          판타지     
41   겟 레디 위드 미            순정      
42   아티스트                 드라마     
43   계약우정                 드라마     
44   아비무쌍                 무협      
45   지옥사원                 드라마     
46   왕 그리고 황제             드라마     
47   인간을 먹는 성             판타지     
48   나는 엄마다               드라마     
49   아버지의 복수는 끝이 없어라      스릴러     
50   노력의 卍(만)             판타지     
51   죽어도! 치우              액션      
52   용의주도 황비              순정      
53   금수친구들                코믹      
54   설공찬전                 순정      
55   Breaker.Drawing      순정      
56   말하지 말까               순정      
57   해치지않아                드라마     
58   하나하나둘                순정      
59   콜로세움                 액션      
60   4학년                  스릴러     
61   키스해주세요               순정      
62   토이 콤플렉스              순정      
63   대나무숲에서 알립니다          스릴러     
64   돈나무                  스릴러     
65   우리가 사랑하는 방법          순정      
66   후크                   판타지     
67   헤븐즈 소울               액션      
68   동쪽으로                 판타지     
69   쌍갑포차                 드라마     
70   이게뭐야                 코믹      
71   수의 계절                판타지     
72   블랙 베히모스              판타지     
73   창백한 말                판타지     
74   살어리랏다                스릴러     
75   고교호구왕                스포츠     
76   스타의 학교생활             학원      
77   냥냐라냥냥                일상      
78   메모리스트                미스터     
79   옆집남자                 순정      
80   신의 태궁                순정      
81   재벌과의 인터뷰             순정      
82   이담                   스릴러     
83   19                   스릴러     
84   샬롯에게는 다섯 명의 제자가 있다   판타지     
85   특별직                  액션      
86   개같은 세상               판타지     
87   저기요 손님               드라마     
88   블랙윈터                 순정      
89   승은이 망극하옵니다           판타지     
90   배고픈 자들의 도시           판타지     
91   겨울과 봄사이              순정      
92   경이로운 소문              판타지     
93   단짠남녀                 순정      
94   구리의 구리구리 컴백          코믹      
95   프레너미                 스포츠     
96   아빠는 변태중              코믹      
97   뽀짜툰                  코믹      
98   불러줘 내 이름만            순정      
99   쓰레기 머학생              일상      
100  미완결                  성인      
101  이태원 클라쓰              드라마     
102  그림자정원                공포      
103  열무와 알타리              일상      
104  랑데부                  액션      
105  닭은 의외로 위대하다          드라마     
106  인스타러브                순정      
107  남남                   드라마     
108  너에게 투 혼(魂)!          학원      
109  나만 아는 사랑             순정      
110  ONE                  액션      
111  어둠이 걷힌 자리엔           미스터     
112  오늘도 꽐랄라라             드라마     
113  키몽의 호구로운 생활          코믹 

In [181]:
# 학습 후 test accuracy 적용
text_clf.fit(df_daum['content1'], df_daum['genre1'])

daum_webtoon_info_test = df_daum(subset='content1',
                              categories='genre1',
                              shuffle=True,
                              random_state=13)
docs_test = daum_webtoon_info_test.content1
predicted = text_clf.predict(docs_test)
np.mean(predicted == daum_webtoon_info_test[genre1])

TypeError: 'DataFrame' object is not callable

In [183]:
# classification report
from sklearn.metrics import classification_report

print(classification_report(daum_webtoon_info_test.target, predicted, 
                           target_names=daum_webtoon_info_test[genre1]))

NameError: name 'daum_webtoon_info_test' is not defined

In [185]:
# confusion matrix
from sklearn.metrics import confusion_matrix

confusion_matrix(daum_webtoon_info_test[genre1], predicted)

NameError: name 'daum_webtoon_info_test' is not defined

In [222]:
# train, test 나누기
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df_n['content1'],
                                                    df_n['genre1'],
                                                    test_size=0.2,
                                                    random_state=44)

In [178]:
# Accuracy 확인
from sklearn.metrics import accuracy_score

y_pred_tr = pipe.predict(x_train)
y_pred_test = pipe.predict(x_test)
print('Train Acc : ', accuracy_score(y_train, y_pred_tr))
print('Test Acc : ', accuracy_score(y_test, y_pred_test))

NameError: name 'pipe' is not defined